stages:
  - build
  - publish

build:
  image: joshkeegan/dotnet-mixed-build:5.1
  stage: build
  script:
    - cd build
    - make build unit-tests-run nuget-create
  artifacts:
    paths:
      - artefacts
      - deploy

publish:
  image: mcr.microsoft.com/dotnet/sdk:5.0.100-buster-slim
  only:
    - release
  stage: publish
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - cd deploy
    - /bin/bash deploy.sh ${NUGET_API_KEY}