stages:
  - build
  - publish

build:
  image: joshkeegan/dotnet-build:2.2.100.0
  stage: build
  script:
    - cd build
    - make build unit-tests-run nuget-create
  artifacts:
    paths:
      - artefacts
      - deploy

publish:
  image: joshkeegan/dotnet-build:2.2.100.0
  only:
    - release
  stage: publish
  dependencies:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - cd deploy
    - ./deploy.sh ${NUGET_API_KEY}